// eeprom.h Code generated by MCC and then put here by PJ
// 2026-04-15 Change signature of WriteByte to get error feedback.

#ifndef EEPROM_H
/**
  @Summary
    Writes a data byte to EEPROM

  @Description
    This routine writes a data byte to given EEPROM address

  @Preconditions
    None

  @Param
    bAdd  - EEPROM location to which data has to be written
    bData - Data to be written to EEPROM address

  @Returns
    0 on success
    1 on failure

  @Example
    <code>
    uint8_t bAdd = 0x10;
    uint8_t bData = 0x55;

    DATAEE_WriteByte(dataeeAddr, dataeeData);
    </code>
*/
int8_t DATAEE_WriteByte(uint16_t bAdd, uint8_t bData);

/**
  @Summary
    Reads a data byte from EEPROM

  @Description
    This routine reads a data byte from given EEPROM address

  @Preconditions
    None

  @Param
    bAdd  - EEPROM address from which data has to be read

  @Returns
    Data byte read from given EEPROM address

  @Example
    <code>
    uint8_t readData;
    uint8_t bAdd = 0x10;
    
    readData = DATAEE_ReadByte(bAdd);
    </code>
*/
uint8_t DATAEE_ReadByte(uint16_t bAdd);
#endif
