// eeprom.c Code generated by MCC for PIC18F26Q10 
// and then placed into this file by PJ.
// 2024-07-13 Adapted to PIC18F46Q71 using description in data sheet.
// 2025-04-15 Clean up and do the writing more carefully.

#include <xc.h>
#include <stdint.h>
#include <stdio.h>

int8_t DATAEE_WriteByte(uint16_t bAdd, uint8_t bData)
// Input:
// bAdd : lower two bytes of the NVM Data byte that we want to write.
// bData : byte data to store.
//
// Returns 0 on success, 1 on failure (as described in data sheet section 10.5.2)
//
// See PIC18F46Q71 data sheet, section 10.4.2, Example 10-10
{
    uint8_t GIEBitValue = INTCON0bits.GIE;
    //Disable interrupts
    INTCON0bits.GIE = 0;
    // Clear error bit before we attempt a write to it.
    NVMCON1bits.WRERR = 0;
    //
    // Set NVMADR with the target word address: 0x380000 - 0x3800FF
    // See data sheet Figure 9-1 Program and Data Memory Map
    NVMADRU = 0x38;
    NVMADRH = (uint8_t)((bAdd & 0xFF00) >> 8);
    NVMADRL = (uint8_t)(bAdd & 0x00FF);
    // Load NVMDATL with desired byte
    NVMDATL = (uint8_t)(bData & 0xFF);
    // Select DATAEE write command.
    NVMCON1bits.CMD = 0b011;
    //
    // Perform the unlock sequence and start the write operation.
    NVMLOCK = 0x55;
    NVMLOCK = 0xAA;
    NVMCON0bits.GO = 1;
    while (NVMCON0bits.GO) { /* wait */ }
    int8_t write_error = NVMCON1bits.WRERR == 0b1;
    //
    // Restore all the interrupts
    INTCON0bits.GIE = GIEBitValue;
    //
    // Disable NVM write command and read back the byte.
    NVMCON1bits.CMD = 0b000;
    NVMCON0bits.GO = 1;
    int8_t data_error = NVMDATL != bData;
    //
    return write_error || data_error;
}

uint8_t DATAEE_ReadByte(uint16_t bAdd)
// See PIC18F46Q71 data sheet, section 10.4.1, Example 10-9
{
    // Set NVMADR with the target word address: 0x380000 - 0x3800FF
    // See data sheet Figure 9-1 Program and Data Memory Map
    NVMADRU = 0x38;
    NVMADRH = (uint8_t)((bAdd & 0xFF00) >> 8);
    NVMADRL = (uint8_t)(bAdd & 0x00FF);
    //
    // Start DATAEE read
    NVMCON1bits.CMD = 0b000;
    NVMCON0bits.GO = 1;
    //
    return NVMDATL;
}
